# Generated by Django 6.0.7 on 2026-08-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('r2_score', models.FloatField()),
                ('mae_score', models.FloatField()),
                ('mse_score', models.FloatField()),
                ('rmse_score', models.FloatField()),
                ('training_time', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Female', max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('program', models.CharField(default='Computer Engineering', max_length=100)),
                ('parental_education', models.CharField(default='Graduate', max_length=50)),
                ('study_hours', models.FloatField(default=18.0)),
                ('attendance', models.FloatField(default=90.0)),
                ('past_score', models.FloatField(default=75.0)),
                ('assignment_score', models.FloatField(default=80.0)),
                ('sleep_hours', models.FloatField(default=7.0)),
                ('extracurricular', models.CharField(default='Yes', max_length=10)),
                ('internet_access', models.CharField(default='Yes', max_length=10)),
                ('final_exam_score', models.FloatField(blank=True, null=True)),
                ('predicted_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(default='Low risk', max_length=20)),
                ('confidence', models.FloatField(default=92.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField()),
                ('predicted_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studentrecord')),
            ],
        ),
    ]
