import { Link } from "react-router-dom";
import { ArrowRight, BrainCircuit, BarChart3, ShieldCheck, Sparkles, Database, Target, TrendingUp, CheckCircle2 } from "lucide-react";
export default function Home(){return <div className="landing">
 <nav className="landing-nav"><Link className="brand" to="/"><div className="brand-mark"><BrainCircuit/></div><div><b>EduPredict</b><span>AI Intelligence</span></div></Link><div className="landing-links"><a href="#features">Capabilities</a><a href="#workflow">How it works</a><a href="#insights">Insights</a><Link to="/login">Sign in</Link><Link className="btn primary" to="/register">Get started <ArrowRight size={17}/></Link></div></nav>
 <section className="hero container"><div className="hero-copy"><div className="pill"><Sparkles size={15}/> AI-powered academic intelligence</div><h1>Predict performance.<br/><em>Improve outcomes.</em></h1><p>Transform student data into actionable insights with machine learning, analytics, and a modern decision-support workspace built for educators.</p><div className="hero-actions"><Link className="btn primary big" to="/dashboard">Explore dashboard <ArrowRight/></Link><a className="btn ghost big" href="#workflow">See how it works</a></div><div className="trust"><span><CheckCircle2/> Explainable predictions</span><span><CheckCircle2/> Secure data workflow</span><span><CheckCircle2/> Research-ready analytics</span></div></div>
 <div className="hero-panel"><div className="panel-glow"></div><div className="prediction-card"><div className="card-head"><span>PERFORMANCE FORECAST</span><span className="live-badge">● LIVE</span></div><div className="score">78.4<span>/100</span></div><div className="score-label">Predicted final exam score</div><div className="meter"><i style={{width:"78%"}}></i></div><div className="confidence"><span>Model confidence</span><b>92.6%</b></div><div className="mini-grid"><div><small>Attendance</small><b>91%</b></div><div><small>Study hours</small><b>18.5/wk</b></div><div><small>Past average</small><b>74.2</b></div></div></div></div></section>
 <section id="features" className="section container"><div className="section-title"><span>ONE INTELLIGENCE LAYER</span><h2>Everything you need to understand performance.</h2></div><div className="feature-grid"><Feature icon={BrainCircuit} title="AI Prediction" text="Estimate final exam performance from academic, demographic, and lifestyle attributes."/><Feature icon={BarChart3} title="Analytics Studio" text="Explore distributions, relationships, trends, correlations, and model insights."/><Feature icon={Database} title="Data Pipeline" text="Import CSV datasets or manage student records through a structured workflow."/><Feature icon={Target} title="Early Intervention" text="Identify students who may need support before performance gaps become critical."/></div></section>
 <section id="workflow" className="section dark-section"><div className="container"><div className="section-title"><span>THE WORKFLOW</span><h2>From raw records to meaningful decisions.</h2></div><div className="steps"><Step n="01" title="Collect" text="Import CSV data or enter records through the Django-backed application."/><Step n="02" title="Prepare" text="Clean missing values, encode categories, and engineer useful features with pandas."/><Step n="03" title="Predict" text="Train and compare regression models using MAE, RMSE, and R²."/><Step n="04" title="Act" text="Use predictions and visual insights to guide academic interventions."/></div></div></section>
 <section id="insights" className="section container"><div className="insight-banner"><div><span>BUILT FOR YOUR ML + FULL-STACK PROJECT</span><h2>Make your student data tell a story.</h2><p>React frontend today. Django REST + scikit-learn backend when you connect your API.</p></div><Link className="btn primary" to="/register">Launch workspace <ArrowRight/></Link></div></section>
 <footer><div>© 2026 EduPredict AI</div><div>Student Performance Prediction & Analytics</div></footer>
 </div>}
function Feature({icon:Icon,title,text}){return <div className="feature"><div className="feature-icon"><Icon/></div><h3>{title}</h3><p>{text}</p><ArrowRight size={18}/></div>}
function Step({n,title,text}){return <div className="step"><b>{n}</b><h3>{title}</h3><p>{text}</p></div>}